produits:
    path:     /
    defaults: { _controller: EcommerceEcommerceBundle:Produit:produits }

presentation:
    path:     /produit
    defaults: { _controller: EcommerceEcommerceBundle:Produit:presentation }
panier:
    path:     /panier
    defaults: { _controller: EcommerceEcommerceBundle:Panier:panier }
livraison:
    path:     /panier/livraison
    defaults: { _controller: EcommerceEcommerceBundle:Panier:livraison }
validation:
    path:     /panier/validation
    defaults: { _controller: EcommerceEcommerceBundle:Panier:validation }
test:
    path:     /test
    defaults: { _controller: EcommerceEcommerceBundle:Test:ajoute }
