parameters:






services:
      tva:
        class: Ecommerce\EcommerceBundle\Twig\Extension\TVAExtension
        public: false
        tags:
            - { name: twig.extension }

      MontantTva:
        class: Ecommerce\EcommerceBundle\Twig\Extension\MontantTvaExtension
        public: false
        tags:
            - { name: twig.extension }

#    ecommerce_ecommerce.example:
#        class: Ecommerce\EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
