<?php

namespace MyUser\UtilisateurBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

     public function findById($id_user)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.id = :id_user')
                        ->setParameter('id_user', $id_user);
        return $qb->getQuery()->getResult();
    }

     public function findByCategorie($idu)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.user = :idu')
                ->orderBy('u.id')
                ->setParameter('id', $idu);
        return $qb->getQuery()->getResult();
    }
}
