produits_index:
    path:     /
    defaults: { _controller: "EcommerceEcommerceBundle:Produits:index" }
    methods:  GET

produits_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceEcommerceBundle:Produits:show" }
    methods:  GET

produits_new:
    path:     /new
    defaults: { _controller: "EcommerceEcommerceBundle:Produits:new" }
    methods:  [GET, POST]

produits_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceEcommerceBundle:Produits:edit" }
    methods:  [GET, POST]

produits_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceEcommerceBundle:Produits:delete" }
    methods:  DELETE
