panier:
    path:     /
    defaults: { _controller: EcommerceEcommerceBundle:Panier:panier }
livraison:
    path:     /livraison
    defaults: { _controller: EcommerceEcommerceBundle:Panier:livraison }
validation:
    path:     /validation
    defaults: { _controller: EcommerceEcommerceBundle:Panier:validation }
supprimer:
    path:  /supprimer/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:supprimer }
ajouter:
    path:  /addProduct/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:ajouteProduit}
catch:
    path:  /addProduct/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:catch}
ajouterPlus:
    path:  /addProduct2/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:ajouteProduit2}
linker:
    path:  /linke/{mavar}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:linked }
payement:
    path:  /finalisation/{montant}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:payer}
generatePDF:
    path:  /facture_pdf
    defaults: { _controller: EcommerceEcommerceBundle:Panier:generatePDF}
DFacture:
    path:  /detail_facture/{id}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:generatePDF }
showfacture:
    path:  /all_facture
    defaults: { _controller: EcommerceEcommerceBundle:Panier:showFacture }
expediction:
    path:  /all_facture/{id}/{iduser}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:expedie }
livraisonfin:
    path:   /all_facture/{id}/{iduser}
    defaults: { _controller: EcommerceEcommerceBundle:Panier:livraisonfinal }
