<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * commandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandesRepository extends \Doctrine\ORM\EntityRepository
{
}
