<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * mediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mediaRepository extends \Doctrine\ORM\EntityRepository
{

   
   
}
