<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * PanierUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierUserRepository extends \Doctrine\ORM\EntityRepository
{
}
