<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * utilisateurAdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurAdresseRepository extends \Doctrine\ORM\EntityRepository
{
}
